# -*- mode: python ; coding: utf-8 -*-

import sys
import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

# Получаем текущую директорию
current_dir = os.getcwd()

# Собираем данные Streamlit
streamlit_datas = collect_data_files('streamlit')

a = Analysis(
    ['launcher.py'],  # Используем launcher.py как главный
    pathex=[current_dir],
    binaries=[],
    datas=[
        ('app.py', '.'),  # Добавляем основной скрипт
    ] + streamlit_datas,
    hiddenimports=[
        'streamlit',
        'streamlit.web',
        'streamlit.web.cli',
        'streamlit.runtime',
        'streamlit.runtime.scriptrunner',
        'streamlit.runtime.scriptrunner.script_runner',
        'streamlit.runtime.scriptrunner.script_cache',
        'streamlit.runtime.state',
        'streamlit.runtime.state.session_state',
        'streamlit.runtime.caching',
        'streamlit.runtime.uploaded_file_manager',
        'streamlit.runtime.media_file_manager',
        'streamlit.runtime.secrets',
        'streamlit.elements',
        'streamlit.elements.media',
        'streamlit.elements.text',
        'streamlit.elements.widgets',
        'streamlit.elements.button',
        'streamlit.elements.dataframe',
        'streamlit.elements.form',
        'streamlit.elements.table',
        'streamlit.delta_generator',
        'streamlit.script_runner',
        'streamlit.source_util',
        'streamlit.watcher',
        'streamlit.watcher.local_sources_watcher',
        'streamlit.watcher.polling_path_watcher',
        'streamlit.watcher.event_based_path_watcher',
        'streamlit.logger',
        'streamlit.config',
        'streamlit.util',
        'streamlit.case_converters',
        'streamlit.color_util',
        'streamlit.credentials',
        'streamlit.delta_util',
        'streamlit.error_util',
        'streamlit.file_util',
        'streamlit.folder_black_list',
        'streamlit.git_util',
        'streamlit.in_memory_file',
        'streamlit.media_file_manager',
        'streamlit.metrics_util',
        'streamlit.net_util',
        'streamlit.notebook_util',
        'streamlit.path_util',
        'streamlit.static',
        'streamlit.temporary_directory',
        'streamlit.type_util',
        'streamlit.url_util',
        'streamlit.version',
        'streamlit.proto',

        # Pandas
        'pandas',
        'pandas._libs',
        'pandas._libs.tslibs',
        'pandas._libs.tslibs.base',
        'pandas._libs.tslibs.conversion',
        'pandas._libs.tslibs.fields',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.offsets',
        'pandas._libs.tslibs.parsing',
        'pandas._libs.tslibs.period',
        'pandas._libs.tslibs.strptime',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.timezones',
        'pandas._libs.tslibs.timestamps',
        'pandas._libs.sparse',
        'pandas._libs.internals',
        'pandas._libs.window',
        'pandas._libs.window.aggregations',
        'pandas._libs.ops',
        'pandas._libs.hashing',
        'pandas._libs.json',
        'pandas._libs.interval',
        'pandas._libs.join',
        'pandas._libs.lib',
        'pandas._libs.missing',
        'pandas._libs.parsers',
        'pandas._libs.properties',
        'pandas._libs.reshape',
        'pandas._libs.writers',
        'pandas._libs.index',
        'pandas._libs.indexing',
        'pandas._libs.ops_dispatch',
        'pandas._libs.tslibs.ccalendar',

        # OpenPyXL
        'openpyxl',
        'openpyxl.cell',
        'openpyxl.cell.cell',
        'openpyxl.cell.read_only',
        'openpyxl.chart',
        'openpyxl.comments',
        'openpyxl.descriptors',
        'openpyxl.drawing',
        'openpyxl.formatting',
        'openpyxl.formula',
        'openpyxl.packaging',
        'openpyxl.pivot',
        'openpyxl.reader',
        'openpyxl.styles',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.writer',
        'openpyxl.xml',

        # NumPy
        'numpy',
        'numpy.core',
        'numpy.core._methods',
        'numpy.core.fromnumeric',
        'numpy.core.numeric',
        'numpy.core.numerictypes',
        'numpy.core.umath',
        'numpy.random',

        # Дополнительные
        'blinker',
        'click',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'altair',
        'jinja2',
        'markdown',
        'toml',
        'cachetools',
        'requests',
        'urllib3',
        'certifi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'scipy',
        'sklearn',
        'tensorflow',
        'torch',
        'jupyter',
        'IPython',
        'sphinx',
        'pytest',
        'tkinter',
        'PyQt5',
        'PyQt6',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='FestivalOfHope',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,  # True для отладки, потом можно сменить на False
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)